version: "3.8"

services:
  tee:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - tee:/app/packages/client-twitter/src/tweetcache
      - tee:/app/db.sqlite
    env_file:
      - .env  # The runtime .env file on the host
    ports:
      - "3000:3000"
    restart: always
    environment:
      TWITTER_DRY_RUN: "false"  # You can override specific variables here if needed

volumes:
  tee: {}
