name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README*'
      - 'CHANGELOG*.md'
      - 'LICENSE*'
      - 'docs/**'
      - '.vscode/**'
      - '.idea/**'
      - '.editorconfig'
      - '**/test/**'
      - '**/__tests__/**'
      - '**/*.spec.*'
      - '**/*.test.*'
      - '.eslint*'
      - '.prettier*'
      - '.circleci/**'
      - '.travis.yml'
      - 'Jenkinsfile'
      - '.gitattributes'
      - '.env.example'
      - 'dist/**'
      - 'build/**'
      - 'coverage/**'
      - '*.log'      
  workflow_dispatch:  # Allows manual triggering as well

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy to Droplet
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Write the SSH private key to a file with proper permissions
          echo "${SSH_PRIVATE_KEY}" > private_key
          chmod 600 private_key

          # SSH into your droplet and run the deployment commands
          ssh -o StrictHostKeyChecking=no -i private_key "$USER_NAME@$SSH_HOST" << 'EOT'
            set -xe

            # Go to your project folder
            cd /root/Twitter-Post-agent

            # 1) Update code from Git
            git reset --hard
            git checkout main
            git pull origin main

            # 2) Remove cache if necessary
            cd agent-new/packages/core
            rm -rf cache

            # 3) Return to the folder with docker-compose.yaml
            cd ../..

            # 4) Rebuild and restart the container
            docker compose down || true
            docker image prune -f
            docker compose up --build -d
          EOT