name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy to Droplet
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key
          chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key $USER_NAME@$SSH_HOST << 'EOT'
            set -xe

            # 1) Go to your project folder on the Droplet
            cd /root/Twitter-Post-agent

            # 2) Ensure we're on main and pull the latest code
            git reset --hard
            git checkout main
            git pull origin main

            # 3) Then go into 'agent' (where docker-compose.yml lives)
            cd agent

            # 4) Bring down containers (but keep volumes)
            docker compose down || true

            # 5) Clean up unused Docker resources (dangling images, etc.)
            docker system prune -f

            # 6) Build and run the container in the background
            docker compose up --build -d
          EOT
